theme: jekyll-theme-minimal
title: Plataforma SITMUN
logo: images/logo.jpg
org: https://github.com/sitmun
org_name: SITMUN
owner_name: Red Europea SITMUN
description: |
  La plataforma SITMUN es una plataforma
  modular de desarrollo de aplicaciones
  de gestión territorial municipal.
exclude:
  - arquitectura
