site_name: Documentación de SITMUN
repo_url: https://github.com/sitmun/sitmun.github.io
repo_name: sitmun/sitmun.github.io
site_url: https://sitmun.github.io

theme:
  name: material
  palette:
    primary: black
  logo: https://raw.githubusercontent.com/sitmun/community/master/Isotip%20SITMUN/PNG/02.principal-transparent-28x28.png
  favicon: https://raw.githubusercontent.com/sitmun/community/master/Isotip%20SITMUN/PNG/02.principal-transparent-28x28.png
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  language: es
  icon:
    repo: fontawesome/brands/github
    admonition:
      info: octicons/browser-16

plugins:
  - search
  - render_swagger
  - autorefs
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
      num_workers: 8
  - print-site:  # Must be the last plugin listed here
     add_to_navigation: true
     print_page_title: 'Versión Imprimible'
     # Table of contents
     add_table_of_contents: true
     toc_title: 'Table of Contents'
     toc_depth: 6

nav:
  - Inicio: index.md
  - Cómo comenzar:
      - getting-started.md
      - Licencia: license.md
  - Referencia:
      - Diseño: design.md
      - API: api.md
      - Gestión: management.md
      - Archivo: archive.md
  - Arquitectura: arquitectura/index.html
  - Contacto: contact.md

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
