site_name: Documentación de SITMUN
site_url: https://sitmun.github.io

theme:
  name: material
  palette:
    primary: black
  logo: https://raw.githubusercontent.com/sitmun/community/master/Isotip%20SITMUN/PNG/02.principal-transparent-28x28.png
  features:
    - navigation.tabs
  language: es
  icon:
    repo: fontawesome/brands/github
    admonition:
      info: octicons/browser-16

plugins:
  - search
  - render_swagger
  - print-site:  # Must be the last plugin listed here
      add_to_navigation: true

nav:
  - Principal: index.md
  - Arquitectura: arquitectura/index.html
  - Gestión: management.md
  - Documentación de las API: https://sitmun-backend-core.herokuapp.com/swagger-ui/index.html
  - Contacto: contacto.md
